config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resource :login, only: [:show, :create, :destroy]

  # Defines the root path route ("/")
  root "main#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/user.rb
class User < ApplicationRecord
  generates_token_for :magic_login, expires_in: 15.minutes do 
    last_sign_in_at
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def authenticate
    Current.user ||= User.find_by(id: session[:user_id])
  end

  def login(user)
    user.touch :last_sign_in_at
    session[:user_id] = user.id
    Current.user = user
  end

  def logout
    session[:user_id] = nil
    Current.user = nil
  end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  def show
    user = User.find_by_token_for(:magic_login, params[:token])
    login(user) if user.present?
    redirect_to root_path
  end

  def create
    user = User.find_by(email: params[:email])
    UserMailer.with(user: user).login.deliver_later if user.present?
    redirect_to root_path, notice: "Check your email to login."
  end

  def destroy
    logout
    redirect_to root_path
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    authenticate
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MagicLogin</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= tag.div notice if notice %>
    <%= tag.div alert if alert %>
    <%= yield %>
  </body>
</html>

app/views/main/index.html.erb
<% if Current.user %>
  <%= button_to "Logout", login_path, method: :delete %>
<% else %>
  <p>Not logged in.</p>

  <h4>Login with email</h4>
  <%= form_with url: login_path, method: :post do |form| %>
    <%= form.email_field :email, placeholder: "tim@apple.com" %>
    <%= form.submit %>
  <% end %>
<% end %>